name: push to docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  push_to_registery:
    name: push to registery
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: action/checkout@v3
      - name: login in to docker
        uses: docker/login-action@v3.3.0
        with:
          username: suarim
          password: qwerty123@@
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: push to docker
        uses:  docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: suarim/my-node-app:latest
      - name: echoing
        run: echo "completed successfully"
      - name: logout
        run: docker logout
        
